=begin
#Simple Inventory API

#This is a simple API

OpenAPI spec version: 1.0.0
Contact: you@your-company.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0

=end

module SwaggerClient
  VERSION = '1.0.0'
end
