=begin
#Simple Inventory API

#This is a simple API

OpenAPI spec version: 1.0.0
Contact: you@your-company.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::DevelopersApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DevelopersApi' do
  before do
    # run before each test
    @instance = SwaggerClient::DevelopersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DevelopersApi' do
    it 'should create an instance of DevelopersApi' do
      expect(@instance).to be_instance_of(SwaggerClient::DevelopersApi)
    end
  end

  # unit tests for search_inventory
  # searches inventory
  # By passing in the appropriate options, you can search for available inventory in the system 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :search_string pass an optional search string for looking up inventory
  # @option opts [Integer] :skip number of records to skip for pagination
  # @option opts [Integer] :limit maximum number of records to return
  # @return [Array<InventoryItem>]
  describe 'search_inventory test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
